{% set name = "ecpy" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cslashm/ECPy/archive/refs/tags/{{ version }}.tar.gz
  sha256: 02a2e990fe4b9c51a5a2d7518439ad80e5d839c931f76fa5144c50543e6a103f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - ecpy
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  downstreams:
    - xrpl-py

about:
  home: https://github.com/cslashm/ECPy
  summary: 'ECPy (pronounced ekpy), is a pure python Elliptic Curve library'
  description: |
    ECPy (pronounced ekpy), is a pure python Elliptic Curve library providing ECDSA, 
    EDDSA (Ed25519), ECSchnorr, Borromean signatures as well as Point operations.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MementoRC
